### ISSUE TITLE
when to release the code?

### ISSUE THREAD

**Issue by zhang-mohole** [NVlabs/Dancing2Music#1]
Hey there, your work is so interesting! So when shall you release the source code?

**Comment by HsinYingLee** [comment]
Thank you for your interest. Currently, the materials are underdoing legal process. We will release it ASAP.

**Comment by stonyhu** [comment]
Interesting work! looking forward to your code and data.

**Comment by akturtle** [comment]
Looks awsome.  Looking forward to your code and data.

**Comment by lizhaoliu** [comment]
Any updates on the code/data release timeline? Also would you release pre-trained models docker images?

Thanks!

**Comment by michael-wzhu** [comment]
Looks awsome. Looking forward to your code and data.

**Comment by Ai-is-light** [comment]
Looking forward to your code and data.

**Comment by ronaldluc** [comment]
I understand the hassles with publishing any data. Would it please be possible to release the code first?
Thanks, I would love to try using it for a rhytm-game levels generation!

**Comment by HsinYingLee** [comment]
Hi all, I'm very sorry for the delay. The code release is now stuck in the legal review. We're pushing the process with our best efforts.

**Comment by eSaniello** [comment]
Hey,
Any updates? Very nice project!

**Comment by ronaldluc** [comment]
Am I seeing things or is the code here? 🎉

**Comment by ghost** [comment]
training code but no pertrained models

**Comment by HsinYingLee** [comment]
Hi all, due to some unresolve issues, please visit my personal [webpage](http://vllab.ucmerced.edu/hylee/) for the script of downloading data and pretrained models. Please let me know if there's any problem of the link.

**Comment by ghost** [comment]
@HsinYingLee I am getting ModuleNotFoundError: No module named 'preprocess' when running demo.py example

**Comment by ghost** [comment]
@HsinYingLee any update on this issue?

**Comment by netolcc06** [comment]
> @HsinYingLee any update on this issue?

I've managed to obtain the preprocess module from its original source at https://github.com/hplgit/preprocess . There's a quick explanation there on how to install it.

However, I'm having a few problems with this module regarding preprocessing the input audio.

**Comment by wkwan** [comment]
@netolcc06 I don't think that's the right module, that's for markup languages not audio files.

**Comment by netolcc06** [comment]
> @netolcc06 I don't think that's the right module, that's for markup languages not audio files.

You're right. I've tried it and it hasn't worked. Plus that, I've made some changes to the code so I could try not relying on this module, but didn't get right results. Hope we can access it soon.

**Comment by pjxhhhh** [comment]
> > @HsinYingLee any update on this issue?
> 
> I've managed to obtain the preprocess module from its original source at https://github.com/hplgit/preprocess . There's a quick explanation there on how to install it.
> 
> However, I'm having a few problems with this module regarding preprocessing the input audio.

Thanks for the solution from https://github.com/hplgit/preprocess

**Comment by netolcc06** [comment]
> > > @HsinYingLee any update on this issue?
> > 
> > 
> > I've managed to obtain the preprocess module from its original source at https://github.com/hplgit/preprocess . There's a quick explanation there on how to install it.
> > However, I'm having a few problems with this module regarding preprocessing the input audio.
> 
> Thanks for the solution from https://github.com/hplgit/preprocess

It's a different module. This is not the one. :/

**Comment by HsinYingLee** [comment]
Hi all, 
The preprocess code is adopted from the Obama [Libsync project](https://github.com/mrmotallebi/synthesizing_obama_network_training). The proprocess.py and mfcc_rev.py can be found there.
