### ISSUE TITLE
Details about FID evaluation

### ISSUE THREAD

**Issue by guofeisun** [NVlabs/Dancing2Music#2]
Hi, your work is very interesting. I'd like to know how you evaluate FID on generated dances.
In table 1, you evaluated FID on real dances and generated dances.
For real dances, do you evaluate FID on test dance data and training dance data?
For generated dances, do you also evaluate FID on generated dances and training dance data?

**Comment by HsinYingLee** [comment]
Yes. We've tried other setting like:
1. Split the training data to two parts (A, B). Measure the FID with (generated, A) for fake and (A, B) for real.
2. Measure FID of fake by (generated, testing).
Numbers are slightly different but the trend is the same.
