### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: './logs\\Decomp'  &  demo.py: error: argument --thr: invalid int value: 'THR'

### ISSUE THREAD

**Issue by farzadmohseni-ir** [NVlabs/Dancing2Music#20]
**When Run any of the following codes , I encounter errors .
Help fix the error ...**

```python
python train_decomp.py --name Decomp
```

> FileNotFoundError: [WinError 3] The system cannot find the path specified: './logs\\Decomp'
> 
> ![image](https://user-images.githubusercontent.com/57835828/119099536-3e363780-ba2c-11eb-8f67-3eb706f486a8.png)

**&**

```python
python train_comp.py --name Decomp --decomp_snapshot DECOMP_SNAPSHOT
```

> FileNotFoundError: [WinError 3] The system cannot find the path specified: './logs\\Decomp'
> 
> ![image](https://user-images.githubusercontent.com/57835828/119099273-fd3e2300-ba2b-11eb-956f-970255a1e635.png)

**&**

```python
python demo.py --decomp_snapshot DECOMP_SNAPSHOT --comp_snapshot COMP_SNAPSHOT --aud_path AUD_PATH --out_file OUT_FILE --out_dir OUT_DIR --thr THR
```

> demo.py: error: argument --thr: invalid int value: 'THR'
> 
> ![image](https://user-images.githubusercontent.com/57835828/119098958-a9333e80-ba2b-11eb-829f-00f13315a7a6.png)

**Comment by hankinghu** [comment]
i meet the same matter , have you solve ?
