### ISSUE TITLE
Missing aud_3cls.ckpt

### ISSUE THREAD

**Issue by ghost** [NVlabs/Dancing2Music#4]
IOError: [Errno 2] No such file or directory: './data/stats/aud_3cls.ckpt'

**Comment by HsinYingLee** [comment]
The ckpt is under the downloaded "stats" folder.

**Comment by Ai-is-light** [comment]
@HsinYingLee you mean, the aud_3cls.ckpt is in the Model_MY.zip?
I do not find the *.ckpt named aud_3cls.ckpt
