### ISSUE TITLE
Operands could not be broadcast together

### ISSUE THREAD

**Issue by FinnRG** [NVlabs/Dancing2Music#8]
I tried executing the command in README and got the following error:

Traceback (most recent call last):
  File "demo.py", line 128, in <module>
    aud[j] = (aud[j] - mean_aud) / std_aud
ValueError: operands could not be broadcast together with shapes (15,) (28,)

**Comment by zhiqizhang** [comment]
I also have this problem. It looks like the MFCC preprocess.py is not using the right function. In the paper the authors talked about "We then extract the 13-dimensional MFCC feature, and concatenate it with its first temporal derivatives and log mean energy of volume into the final 28-dimensional audio feature." That explains why the mean_aud and std_aud has the (28, )shape. but the aud we get from the preprocess is default MFCC 13 dimension + two other values as defined in sig2s2mfc_energy() function from preprocess.py  
I can't find any code that calculate the "first temporal derivatives". Can somebody show where is the code? thanks.

**Comment by gagolucasm** [comment]
Same error here, it's a nightmare to reproduce this code

**Comment by Ai-is-light** [comment]
> I also have this problem. It looks like the MFCC preprocess.py is not using the right function. In the paper the authors talked about "We then extract the 13-dimensional MFCC feature, and concatenate it with its first temporal derivatives and log mean energy of volume into the final 28-dimensional audio feature." That explains why the mean_aud and std_aud has the (28, )shape. but the aud we get from the preprocess is default MFCC 13 dimension + two other values as defined in sig2s2mfc_energy() function from preprocess.py
> I can't find any code that calculate the "first temporal derivatives". Can somebody show where is the code? thanks.

I check the source code, but have the same isuue

**Comment by Ai-is-light** [comment]
we must use the special music*.wav as input?

**Comment by Ai-is-light** [comment]
> Same error here, it's a nightmare to reproduce this code

@gagolucasm have you dealt with it?

**Comment by HsinYingLee** [comment]
I put a zipped file of the complete demo code on my [personal webpage](http://vllab.ucmerced.edu/hylee/).

**Comment by caijianfei** [comment]
> I put a zipped file of the complete demo code on my [personal webpage](http://vllab.ucmerced.edu/hylee/).

great, thx very much
